name: markdown
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
        config_file: ".markdownlint.json"
